name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    name: Ruby ${{ matrix.ruby }} @ Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4']
        rails: ['~> 7.2', '~> 8.0', '~> 8.1.0.beta1']
      fail-fast: false  # Ensures that all matrix jobs continue even if one fails
    env:
      RAILS_ENV: test
      RAILS_VERSION: ${{ matrix.rails }}
    services:
      postgres:
        image: 'postgres:16'
        ports: ['5439:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: 'mysql:8.0'
        ports: ['3309:3306']
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run all test
        run: make test_all
