name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} @ Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ['3.2.6', '3.3.6']
        rails: ['~> 7.2', '~> 8.0']
      fail-fast: false  # Ensures that all matrix jobs continue even if one fails
    env:
      RAILS_ENV: test
      RAILS_VERSION: ${{ matrix.rails }}
    services:
      postgres:
        image: 'postgres:16'
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ubuntu
          POSTGRES_DB: db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: 'mysql:8.0'
        ports: ['3306:3306']
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_test
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Database Setup
        run: bin/setup
      - name: Execute Tests
        run: bin/rails test
