name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.6'
          - '3.3.6'
        rails:
          - '~> 7.2'
          - '~> 8.0'
    env:
      RAILS_ENV: test
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run test
        run: bin/rails test

